# Generated by Django 3.2.5 on 2021-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "created_on",
                    models.DateTimeField(auto_now=True, verbose_name="date published"),
                ),
                ("active", models.BooleanField(default=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
